# Generated by Django 4.2 on 2023-04-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="nickname",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
